# Generated by Django 5.2.3 on 2025-06-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='detail_description',
            field=models.TextField(blank=True, null=True, verbose_name='Подробное описание'),
        ),
    ]
