# Generated by Django 5.2.3 on 2025-07-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_task_detail_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='compelet_date',
            new_name='complete_date',
        ),
    ]
