# Generated by Django 5.2.3 on 2025-07-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_task_complete_date_task_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=30, verbose_name='Краткое описание'),
        ),
    ]
