# Generated by Django 5.2.3 on 2025-07-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ManyToManyField(related_name='tasks', to='webapp.type', verbose_name='Тип'),
        ),
    ]
