# Generated by Django 5.2.3 on 2025-07-20 15:44

from django.db import migrations

def project_binding(apps, schema_editor):
    Project = apps.get_model('webapp', 'Project')
    Task = apps.get_model('webapp', 'Task')
    project = Project.objects.create(name='First project',
                                     description='This is the first project',
                                     start_date='2025-07-20')
    for task in Task.objects.all():
        task.project = project
        task.save()

def rollback_project_binding(apps, schema_editor):
    Project = apps.get_model('webapp', 'Project')
    Task = apps.get_model('webapp', 'Task')
    for task in Task.objects.all():
        task.project = None
        task.save()
    Project.objects.get(name='First project').delete()




class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_project_alter_task_status_alter_task_type_and_more'),
    ]

    operations = [
        migrations.RunPython(project_binding, rollback_project_binding),
    ]
